# Generated by Django 4.2 on 2023-04-17 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movieorder_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="order",
            new_name="user",
        ),
    ]
